/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : BASE64
 #	author : miyako
 #	2017/03/27
 #
 # --------------------------------------------------------------------------------*/



// --- BASE64
void BLOB_to_base64(sLONG_PTR *pResult, PackagePtr pParams);
void BLOB_from_base64(sLONG_PTR *pResult, PackagePtr pParams);
void BLOB_to_hex(sLONG_PTR *pResult, PackagePtr pParams);
void BLOB_from_hex(sLONG_PTR *pResult, PackagePtr pParams);
